---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: install cobbler
  package: name={{ item }} state=latest
  with_items: "{{ cobbler_packages }}"

- name: start and enable cobbler
  service: name={{ cobbler_service }} state=started enabled=yes
